version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - FLASK_ENV=development
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
